### ISSUE TITLE
Generate docs not yet successfully

### ISSUE THREAD

**Issue by aprilaugust** [BeamIO-Inc/resippy#37]
Thanks a lot for your great efforts for building resippy.
I have tried to generate documents based on your README guide. 
All package dependencies are installed. 
Here is my system spec.
![image](https://user-images.githubusercontent.com/52404237/69848470-26f21000-12b5-11ea-80dd-19ce6ecb81d4.png)

And here is the errors when I `sudo make html`

(resippy) ndk@ndk-X1:~/Downloads/resippy/docs$ sudo make html
[sudo] password for ndk: 
Creating file _modules/resippy.rst.
Creating file _modules/resippy.image_objects.rst.
Creating file _modules/resippy.image_objects.earth_overhead.rst.
Creating file _modules/resippy.image_objects.earth_overhead.digital_globe.rst.
Creating file _modules/resippy.image_objects.earth_overhead.digital_globe.view_ready_stereo.rst.
Creating file _modules/resippy.image_objects.earth_overhead.earth_overhead_point_calculators.rst.
Creating file _modules/resippy.image_objects.earth_overhead.geotiff.rst.
Creating file _modules/resippy.image_objects.earth_overhead.micasense.rst.
Creating file _modules/resippy.image_objects.earth_overhead.physical_camera.rst.
Creating file _modules/resippy.image_objects.envi.rst.
Creating file _modules/resippy.image_recognition.rst.
Creating file _modules/resippy.image_recognition.neural_net_model_scoring.rst.
Creating file _modules/resippy.image_recognition.neural_net_model_training.rst.
Creating file _modules/resippy.photogrammetry.rst.
Creating file _modules/resippy.photogrammetry.dem.rst.
Creating file _modules/resippy.photogrammetry.nav.rst.
Creating file _modules/resippy.spectral.rst.
Creating file _modules/resippy.spectral.spectrum_factories.rst.
Creating file _modules/resippy.spectral.spectrum_factories.SVC.rst.
Creating file _modules/resippy.spectral.spectrum_factories.SVC.ascii.rst.
Creating file _modules/resippy.spectral.spectrum_factories.csv.rst.
Creating file _modules/resippy.spectral.spectrum_factories.csv.ascii.rst.
Creating file _modules/resippy.spectral.spectrum_factories.envi.rst.
Creating file _modules/resippy.spectral.spectrum_factories.envi.ascii.rst.
Creating file _modules/resippy.spectral.spectrum_factories.usgs.rst.
Creating file _modules/resippy.spectral.spectrum_factories.usgs.ascii.rst.
Creating file _modules/resippy.test_runner.rst.
Creating file _modules/resippy.test_runner.demo_tests.rst.
Creating file _modules/resippy.test_runner.demos.rst.
Creating file _modules/resippy.test_runner.tests.rst.
Creating file _modules/resippy.test_runner.timings.rst.
Creating file _modules/resippy.utils.rst.
Creating file _modules/resippy.utils.image_utils.rst.
Creating file _modules/resippy.utils.units.rst.
Creating file _modules/modules.rst.
Running Sphinx v1.3.6
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 37 source files that are out of date
updating environment: 37 added, 0 changed, 0 removed
TEST CHIPPER TESTS [ 75%] _modules/resippy.test_runner                                                              

E
E
E
E
E
E
SPECTRUM FACTORY TEST: ASD
E
STARTING SPECTRUM FACTORY TEST: AVIRIS
E
======================================================================
ERROR: test_bands (test_chipper.TestChipper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ndk/Downloads/resippy/resippy/test_runner/demo_tests/test_chipper.py", line 21, in setUp
    self.png_image_data = imread(self.png_fullpath)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 173, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 126, in __init__
    self._parse_uri(uri)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 278, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/home/ndk/Data/resippy_demo_data/image_data/overhead_vehicle_data/Potsdam_ISPRS/top_potsdam_2_14_RGB.png'

======================================================================
ERROR: test_chip_by_centers (test_chipper.TestChipper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ndk/Downloads/resippy/resippy/test_runner/demo_tests/test_chipper.py", line 21, in setUp
    self.png_image_data = imread(self.png_fullpath)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 173, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 126, in __init__
    self._parse_uri(uri)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 278, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/home/ndk/Data/resippy_demo_data/image_data/overhead_vehicle_data/Potsdam_ISPRS/top_potsdam_2_14_RGB.png'

======================================================================
ERROR: test_grayscale (test_chipper.TestChipper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ndk/Downloads/resippy/resippy/test_runner/demo_tests/test_chipper.py", line 21, in setUp
    self.png_image_data = imread(self.png_fullpath)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 173, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 126, in __init__
    self._parse_uri(uri)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 278, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/home/ndk/Data/resippy_demo_data/image_data/overhead_vehicle_data/Potsdam_ISPRS/top_potsdam_2_14_RGB.png'

======================================================================
ERROR: test_keep_within_bounds (test_chipper.TestChipper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ndk/Downloads/resippy/resippy/test_runner/demo_tests/test_chipper.py", line 21, in setUp
    self.png_image_data = imread(self.png_fullpath)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 173, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 126, in __init__
    self._parse_uri(uri)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 278, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/home/ndk/Data/resippy_demo_data/image_data/overhead_vehicle_data/Potsdam_ISPRS/top_potsdam_2_14_RGB.png'

======================================================================
ERROR: test_lower_right (test_chipper.TestChipper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ndk/Downloads/resippy/resippy/test_runner/demo_tests/test_chipper.py", line 21, in setUp
    self.png_image_data = imread(self.png_fullpath)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 173, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 126, in __init__
    self._parse_uri(uri)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 278, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/home/ndk/Data/resippy_demo_data/image_data/overhead_vehicle_data/Potsdam_ISPRS/top_potsdam_2_14_RGB.png'

======================================================================
ERROR: test_overlap (test_chipper.TestChipper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ndk/Downloads/resippy/resippy/test_runner/demo_tests/test_chipper.py", line 21, in setUp
    self.png_image_data = imread(self.png_fullpath)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/functions.py", line 173, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 126, in __init__
    self._parse_uri(uri)
  File "/usr/local/lib/python3.5/dist-packages/imageio/core/request.py", line 278, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/home/ndk/Data/resippy_demo_data/image_data/overhead_vehicle_data/Potsdam_ISPRS/top_potsdam_2_14_RGB.png'

======================================================================
ERROR: test_aviris (test_spectral_factories.TestASDReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ndk/Downloads/resippy/resippy/test_runner/demo_tests/test_spectral_factories.py", line 79, in test_aviris
    fullpath = glob.glob(spectrum_dir + "/*" + self.test_spectrum_fname_part + "*")[0]
IndexError: list index out of range

======================================================================
ERROR: test_aviris (test_spectral_factories.TestAvirisReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ndk/Downloads/resippy/resippy/test_runner/demo_tests/test_spectral_factories.py", line 40, in test_aviris
    fullpath = glob.glob(spectrum_dir + "/*" + self.test_spectrum_fname_part + "*")[0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 8 tests in 0.005s

FAILED (errors=8)
SHAPE CONSISTENCY TEST

shape consistency test passed
microflicks unit test passed
.microns unit test passed
.Fsetting fixture roll to 5 degrees and camera boresight roll to -5 degrees results in a zero camera roation
roll boresight test passed.
.setting fixture yaw to 5 degrees and camera boresight yaw to -5 degrees results in a zero camera roation
pitch boresight test passed.
.setting fixture to 5 degrees and camera boresight yaw to -5 degrees results in a zero camera rotation
yaw boresight test passed.
./home/ndk/Downloads/resippy/resippy/image_objects/earth_overhead/earth_overhead_point_calculators/abstract_earth_overhead_point_calc.py:250: RuntimeWarning: overflow encountered in square
  np.square(machine_pixels_lat_y_diff) > np.square(d_pixel))[0])[0]
positive pitch results in camera center pointing to a higher latitude
makes sense by right-hand-rule conventions.
a positive y lever arm offset with a positive roll results in the camera moving higher in altitude and lower in latitude.
test passed.
./home/ndk/Downloads/resippy/resippy/image_objects/earth_overhead/earth_overhead_point_calculators/abstract_earth_overhead_point_calc.py:244: RuntimeWarning: overflow encountered in square
  lon_gt1_pixel_index = (np.where(np.square(machine_pixels_lon_x_diff) +
/home/ndk/Downloads/resippy/resippy/image_objects/earth_overhead/earth_overhead_point_calculators/abstract_earth_overhead_point_calc.py:245: RuntimeWarning: overflow encountered in square
  np.square(machine_pixels_lon_y_diff) > np.square(d_pixel))[0])[0]
/home/ndk/Downloads/resippy/resippy/image_objects/earth_overhead/earth_overhead_point_calculators/abstract_earth_overhead_point_calc.py:245: RuntimeWarning: overflow encountered in add
  np.square(machine_pixels_lon_y_diff) > np.square(d_pixel))[0])[0]
/home/ndk/Downloads/resippy/resippy/image_objects/earth_overhead/earth_overhead_point_calculators/abstract_earth_overhead_point_calc.py:249: RuntimeWarning: overflow encountered in square
  lat_gt1_pixel_index = (np.where(np.square(machine_pixels_lat_x_diff) +
/home/ndk/Downloads/resippy/resippy/image_objects/earth_overhead/earth_overhead_point_calculators/abstract_earth_overhead_point_calc.py:250: RuntimeWarning: overflow encountered in add
  np.square(machine_pixels_lat_y_diff) > np.square(d_pixel))[0])[0]
last pixel in the array is in the positive longitude direction at roll=0, pitch=0, yaw=0
a positive yaw rotation results seem correct from the perspective of pixel shift
a positive yaw moves a camera originally located at (1, 0, 0) relative to the fixture to a greater y location and lower x location.
yaw rotation tests passed.
.positive roll results in camera center pointing to a higher latitude
makes sense by right-hand-rule conventions.
a positive y lever arm offset with a positive roll results in the camera moving higher in altitude and lower in latitude.
test passed.
.created shapely polygon, bounds are correct.
geom_utils bounds test passed.
..datatype tests passed
.image from from numpy array test passed
.offsets solver test passed
.solved for case where omega is positive, phi is positive, kappa is positive.
solved for case where omega is positive, phi is positive, kappa is negative.
solved for case where omega is positive, phi is negative, kappa is positive.
solved for case where omega is positive, phi is negative, kappa is negative.
solved for case where omega is negative, phi is positive, kappa is positive.
solved for case where omega is negative, phi is positive, kappa is negative.
solved for case where omega is negative, phi is negative, kappa is positive.
solved for case where omega is negative, phi is negative, kappa is negative.
.reproject geometry test passed
.shift by meters test passed
..solved values for omega, phi and kappa are within 1.e-15
.confirming rotation order for standard photogrammetric operations:
the correct order of operations for:
(first rotation) omega, then (second rotation) phi, then (third rotation) kapa is:
m_kappa @ m_phi @ m_omega
or
np.matmul(m_kappa, np.matmul(m_phi, m_omega))
.
ACE TEST 1D
1D ACE TEST PASSED
.
ACE TEST 2D
.
COVARIANCE EQUALIZATION TARGET DETECTION TEST
COVARIANCE EQUALIZATION TARGET DETECTION TEST PASSED
.
COVARIANCE EQUALIZATION TEST
COVARIANCE EQUALIZATION TEST PASSED
.
FLATTEN IMAGE CUBE TEST
flattening and unflattening image cube matches with original
.
MASKED COVARIANCE TEST 1D
MASKED_COVAR_1D TEST PASSED
.
MASKED COVARIANCE TEST 2D
MASKED COVAR 2D TEST PASSED
.
MASKED MEAN TEST 1D
MASKED MEAN TEST 1D - TEST PASSED
.
MASKED MEAN TEST 2D
.
RX ANAMOLY TEST 1D
1d rx passed 

.
RX ANAMOLY TEST 2D
.
SAM TEST 1D
1-D SAM TEST PASSED
.
SAM TEST 2D
2d sam test passed.
.
SAM / ACE EQUALITY TEST WHEN INVERSE COVARIANCE IS IDENTITY
ACE / SAM comparison test passed.
.
SAM / ACE COMPARISON AND SANITY CHECK TEST
SAM / ACE SANITY CHECK TEST PASSED
..
======================================================================
FAIL: test_fixture_pitch_boresight (test_fixtured_camera.TestFixturedCamera)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ndk/Downloads/resippy/resippy/test_runner/tests/test_fixtured_camera.py", line 37, in test_fixture_pitch_boresight
    assert np.isclose(roll, 0)
AssertionError

----------------------------------------------------------------------
Ran 36 tests in 3.489s

FAILED (failures=1)
TEST CHIPPER TESTS [ 78%] _modules/resippy.test_runner.demo_tests                                                   
ERROR 4: /home/ndk/Data/resippy_demo_data/image_data/digital_globe/Tripoli_View-Ready_Stereo_8_Band_Bundle_30cm/056082094030/056082094030_01_P001_MUL/15AUG31100732-M2AS-056082094030_01_P001.TIF: No such file or directory
ERROR 4: /home/ndk/Data/resippy_demo_data/image_data/digital_globe/Tripoli_View-Ready_Stereo_8_Band_Bundle_30cm/056082094030/056082094030_01_P001_MUL/15AUG31100732-M2AS-056082094030_01_P001.TIF: No such file or directory
SHAPE CONSISTENCY TEST3%] _modules/resippy.test_runner.tests                                                        

shape consistency test passed
reading sources... [100%] index                                                                                     

Sphinx error:
master file /home/ndk/Downloads/resippy/docs/contents.rst not found
Makefile:22: recipe for target 'html' failed
make: *** [html] Error 1

I highly appreciate for any support.
Thank you.

**Comment by jcasey-beamio** [comment]
Hello,
This is an issue we need to fix.  Currently all tests are bundled within the project.  When sphinx tries to build the docs it also tries to run all the tests, some of which rely on external data that you won't have.  If you move the "test_runner" directory out of the project and try to build again it will likely work.  If that doesn't work we can try to coordinate a way to get you docs, maybe through email.

**Comment by aprilaugust** [comment]
Hi @jcasey-beamio,

I'm very glad to receive your message.
I follow your suggestion & remove "test_runner", then build again. 
Unfortunately, it still doesn't work yet.

Screenshot:
![image](https://user-images.githubusercontent.com/52404237/71625093-eae9fc00-2c20-11ea-950d-095b7c8608a0.png)

![image](https://user-images.githubusercontent.com/52404237/71625104-048b4380-2c21-11ea-9adf-7712240219d6.png)

Would you please mind helping to provide the docs via my email (khoanguyen07ts@gmail.com)?
I highly appreciate your support.

Thank you & Happy New Year :))
Best,
Khoa
